language: python
dist: trusty
sudo: required

services:
  - docker

before_install:
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
  - sudo apt-get update -qq
  - sudo apt-get install -y shellcheck
  - sudo apt-get install -y -o Dpkg::Options::="--force-confold" --force-yes docker-engine

install:
  - pip install ansible ansible-container

script:
  - docker version
  - docker-compose version
  - docker info
  - ansible-container build
  - ansible-container run -d
  - docker ps -a
  - docker images
  - cd test && ansible-playbook -i inventory test.yml
  - cd .. && ansible-container stop -f

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
